name: Node.js Matrix Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]
        exclude:
          - os: windows-latest
            node: 14
        include:
          - os: ubuntu-latest
            node: 18

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run tests on Node.js ${{ matrix.node }} at ${{ matrix.os }}
        run: npm test
