name: Storing artifact

on:
  push:

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay program
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" > dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dragon-text-file
          path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4.3.0
        with:
          name: dragon-text-file
          path: ./artifact

      - name: Test file exists
        run: grep -i dragon "./artifact/dragon.txt"

  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4.3.0
        with:
          name: dragon-text-file
          path: ./artifact

      - name: Read file
        run: cat ./artifact/dragon.txt

      - name: Deploy
        run: echo Deploying ... .. .
