name: Build and Deploy Node.js App

on:
  workflow_dispatch:

env:
  IMAGE_NAME: nodejs-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Container
        run: |
          docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker run -d -p 3000:3000 ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
